
export const DATA = "data"
export const ITEMS = "Items"
export const ENTER = "ENTER"
export const RESET = "RESET"
export const AMOUNT = "Amount"
export const CHANGE = "Change"
export const NUMBER = "Number"
export const DARK = "dark"
export const LIGHT = "light"
export const SUCCESS = "success"
export const FIALED = "failed"
export const LOADING = "loading"
export const IDLE = "idle"
export const ADD_MORE_FUNDS = "add more funds"
export const AMOUNT_SLICE = "amount"
export const NETWORK_RESPONS_NOT_OK = "Network response was not ok"